### ISSUE TITLE
Mongo is Empty

### ISSUE THREAD

**Issue by ghost** [CSCI-4830-002-2014/challenge-week-9#2]
Hi all,

When I run the script from last lab, my output on the terminal is fine. However, when I go to my database in Mongo and try to query it, it appears to be empty.  My collection that I named in my script is called "course_events".  Below is a screen shot of what happens when I try to count it:

![image](https://cloud.githubusercontent.com/assets/8551620/4777527/a950de28-5bd1-11e4-9aef-ffc8c41fc063.png)

Is there something I am missing?

**Comment by wannabeCitizen** [comment]
Are you sure you actually saved the data?  Have you queried it before to
ensure the data was in there?

**Comment by ghost** [comment]
I played around a bit with Mongo on the command line and got it to work. I think the problem might have been that I was not on the right db. Thanks for your help.
